name: "Open Graph"

on:
  workflow_dispatch:

jobs:
  images:
    name: Images
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install           \
            jq                           \
            sqlite3                      \
            libparallel-forkmanager-perl \
            libapp-options-perl          \
            libencode-perl               \
            libyaml-libyaml-perl         \
            libjson-xs-perl              \
            libdbd-csv-perl              \
            libdbd-sqlite3-perl          \
            libtemplate-perl             \
            libgd-perl                   \
            fonts-roboto

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Google Cloud SDK
        env:
          GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }}
          GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
        run: |
          echo "$GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY" > "/tmp/service_account_key.json" && \
          gcloud auth activate-service-account --key-file="/tmp/service_account_key.json" && \
          gcloud config set project "$GOOGLE_CLOUD_PROJECT_ID"

      - name: Download pricing
        run: |
          cd build || exit 9
          curl -OL "https://github.com/Cyclenerd/google-cloud-pricing-cost-calculator/raw/master/pricing.yml" || exit 9

      - name: Run build script
        run: |
          cd build || exit 9
          bash build.sh || exit 9

      - name: Create images
        run: |
          cd build || exit 9
          perl opengraph.pl --processes=4 || exit 9

      - name: Deploy
        run: gsutil -m rsync -r opengraph gs://opengraph.gcloud-compute.com || exit 9